// Generated by CoffeeScript 1.3.1
(function() {
  var VideoChat,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  VideoChat = (function() {

    VideoChat.name = 'VideoChat';

    function VideoChat() {
      this.webcamWorks = __bind(this.webcamWorks, this);
      this.video = document.querySelector('video');
      this.canvas = document.querySelector('canvas');
      this.ctx = this.canvas.getContext('2d');
      this.width = this.canvas.width;
      this.height = this.canvas.height;
      navigator.webkitGetUserMedia({
        video: true
      }, this.webcamWorks, this.webcamHasError);
    }

    VideoChat.prototype.webcamHasError = function(e) {
      return console.log(e);
    };

    VideoChat.prototype.webcamWorks = function(localMediaStream) {
      this.video.src = window.URL.createObjectURL(localMediaStream);
      return this.init();
    };

    VideoChat.prototype.init = function() {
      var _this = this;
      return window.requestAnimationFrame(function() {
        return _this.renderOtherPerson();
      });
    };

    VideoChat.prototype.renderOtherPerson = function() {
      return this.ctx.drawImage(this.video, 0, 0, this.width, this.height);
    };

    return VideoChat;

  })();

  window.chat = new VideoChat();

}).call(this);
